version: '3.8'

services:

  mysql:
    container_name: mysql
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    volumes:
      - mysql_volume:/var/lib/mysql
      - ./mysql_volume/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_DATABASE=portal
      - MYSQL_ROOT_PASSWORD=fvx9cku!fvw5zxt6VKJ
    ports:
      - '3397:3306'

  redis:
    container_name: redis
    image: redis:6-alpine
    volumes:
      - redis_volume:/data
    ports:
      - 6397:6379

  portal_app:
    container_name: portal_app
    restart: always
    depends_on:
      - mysql
      - redis
    build:
      context: .
      target: dependencies
    ports:
      - ${PORT}:${PORT}
      - 9297:9229
    env_file:
      - .env
    environment:
      - MYSQL_HOST=mysql
      - REDIS_HOST=redis
    volumes:
      - ./src:/home/app
    command: dumb-init node ace serve --watch --node-args="--inspect=0.0.0.0"

volumes:
  mysql_volume:
    driver: local
  redis_volume:
